//! GENERATED by `gen_voltage_catalogue.py` (the `/ofc:superio-curator`
//! toolkit) — do not edit by hand; regenerate it, then `cargo fmt` (VOLT-b,
//! DEC-464).
//!
//! Source: <https://github.com/frankcrawford/it87> at commit
//! `bc06d3488439e5fcd725c1bdcfcac994d6d95cac`, directory `Sensors configs/Gigabyte/configs`:
//! `gigabyte-it87-amd.conf`, `gigabyte-it87-intel.conf`, and — for the X299 boards, whose maps
//! depend on the CPU family — only the inputs on which
//! `gigabyte-it87-intel-kabylakex.conf` and `gigabyte-it87-intel-skylakex.conf` agree.
//! Those files are GPL-2.0; what is carried here is the factual content of
//! their `label inN`, `compute inN` and `ignore inN` lines — which rail each
//! ADC input is wired to on a board, its divider ratio, and which inputs a
//! board's config does not map — keyed exactly as the configs key it.
//! Attribution: `NOTICE.md`.

use super::voltage_catalogue::{named, BoardRail::Unmapped, Stanza};

pub(super) static AMD: &[Stanza] = &[
    // gigabyte-it87-amd.conf:36
    Stanza {
        chips: &[
            ("it8686", 0x1002_0507),
            ("it8686", 0x1202_0507),
            ("it8686", 0x3002_0507),
            ("it8686", 0x3102_0507),
            ("it8689", 0x3202_0507),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:84
    Stanza {
        chips: &[
            ("it8686", 0x1003_0507),
            ("it8686", 0x3003_0507),
            ("it8686", 0x3103_0507),
            ("it8689", 0x3203_0507),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:131
    Stanza {
        chips: &[
            ("it8686", 0x1004_0607),
            ("it8686", 0x3004_0607),
            ("it8686", 0x3104_0607),
            ("it8689", 0x3204_0607),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:170
    Stanza {
        chips: &[("it8686", 0x1005_0607), ("it8686", 0x1105_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:209
    Stanza {
        chips: &[("it8686", 0x1008_090B), ("it8686", 0x3008_090B)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:244
    Stanza {
        chips: &[("it8792", 0x1008_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("Chipset Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VDD18", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:270
    Stanza {
        chips: &[("it8686", 0x2008_090D)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("DRAM CH(C/D)", 1.0)),
            (5, named("CPU VCORE SOC", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:305
    Stanza {
        chips: &[("it8792", 0x2008_090D)],
        rails: &[
            (0, named("CPU VCORE SIO", 1.0)),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("Chipset Core", 1.0)),
            (3, named("5VSB", 2.5)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("DDRVPP CH(C/D)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:336
    Stanza {
        chips: &[("it8686", 0x2108_090D), ("it8686", 0x2208_090D)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("DRAM CH(C/D)", 1.0)),
            (5, named("CPU VCORE SOC", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:374
    Stanza {
        chips: &[("it8792", 0x2108_090D), ("it8792", 0x2208_090D)],
        rails: &[
            (0, named("CPU VCORE SIO", 1.0)),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("Chipset Core", 1.0)),
            (3, named("5VSB", 2.5)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("DDRVPP CH(C/D)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:415
    Stanza {
        chips: &[
            ("it8686", 0x3005_0607),
            ("it8686", 0x3008_0907),
            ("it8686", 0x3105_0607),
            ("it8686", 0x3108_090B),
            ("it8689", 0x3205_0607),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:449
    Stanza {
        chips: &[("it8792", 0x3008_0907)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:474
    Stanza {
        chips: &[("it8792", 0x3008_090B)],
        rails: &[
            (0, named("DDRVTT CH(A/B)", 1.0)),
            (1, named("Chipset Core", 1.0)),
            (2, Unmapped),
            (3, named("CPU VDD18", 1.0)),
            (4, named("Chipset Core 2.5V", 1.649)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:500
    Stanza {
        chips: &[("it8792", 0x3108_090B)],
        rails: &[
            (0, named("DDRVTT CH(A/B)", 1.0)),
            (1, named("Chipset Core", 1.0)),
            (2, Unmapped),
            (3, named("CPU VDD18", 1.0)),
            (4, named("Chipset Core 2.5V", 1.649)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:525
    Stanza {
        chips: &[("it8688", 0x4003_0407)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:562
    Stanza {
        chips: &[("it8688", 0x4005_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:610
    Stanza {
        chips: &[
            ("it8688", 0x4008_090A),
            ("it8688", 0x4108_090B),
            ("it8688", 0x6008_090B),
            ("it8688", 0x6108_090B),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:647
    Stanza {
        chips: &[("it8792", 0x4008_090A), ("it87952", 0x8108_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("Chipset Core", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM_CLDO12", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:678
    Stanza {
        chips: &[
            ("it8688", 0x4008_090B),
            ("it8688", 0x4208_090B),
            ("it8688", 0x4308_090B),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:714
    Stanza {
        chips: &[("it8792", 0x4008_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("Chipset Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM_CLDO12", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:744
    Stanza {
        chips: &[
            ("it8792", 0x4108_090B),
            ("it8792", 0x4208_090B),
            ("it8792", 0x4308_090B),
        ],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("Chipset Core", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM_CLDO12", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:771
    Stanza {
        chips: &[("it8688", 0x5008_090B), ("it8688", 0x5108_090B)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("DRAM CH(C/D)", 1.0)),
            (5, named("CPU Vcore SOC", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:806
    Stanza {
        chips: &[("it8792", 0x5008_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("Chipset Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VDD18", 1.0)),
            (5, named("DDRVPP CH(C/D)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:832
    Stanza {
        chips: &[("it8792", 0x5108_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("Chipset Core", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("DDRVPP CH(C/D)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:857
    Stanza {
        chips: &[("it8688", 0x5208_090B)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("DRAM CH(C/D)", 1.0)),
            (5, named("CPU Vcore SOC", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:891
    Stanza {
        chips: &[("it8792", 0x5208_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("Chipset Core", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("DDRVPP CH(C/D)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:916
    Stanza {
        chips: &[("it8688", 0x5308_090A)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("DRAM CH(C/D)", 1.0)),
            (5, named("CPU Vcore SOC", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:950
    Stanza {
        chips: &[("it8792", 0x5308_090A)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("Chipset Core", 1.0)),
            (4, Unmapped),
            (5, named("DDRVPP CH(C/D)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1003
    Stanza {
        chips: &[
            ("it8688", 0x6003_0507),
            ("it8689", 0x6103_0507),
            ("it8688", 0x7003_0507),
            ("it8689", 0x7103_0507),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:1061
    Stanza {
        chips: &[
            ("it8688", 0x6005_0607),
            ("it8689", 0x6105_0607),
            ("it8688", 0x7005_0607),
            ("it8689", 0x7105_0607),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:1103
    Stanza {
        chips: &[("it8792", 0x6008_090B), ("it8792", 0x6108_090B)],
        rails: &[
            (0, named("DDRVTT CH(A/B)", 1.0)),
            (1, named("Chipset Core", 1.0)),
            (2, Unmapped),
            (3, named("CPU VDD18", 1.0)),
            (4, named("PM_2V5", 1.649)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1136
    Stanza {
        chips: &[
            ("it8689", 0x6102_0507),
            ("it8688", 0x7002_0507),
            ("it8689", 0x7102_0507),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:1185
    Stanza {
        chips: &[
            ("it8688", 0x8003_0407),
            ("it8688", 0x8006_0607),
            ("it8688", 0x8008_090A),
            ("it8688", 0x800A_090A),
            ("it8688", 0x8108_090A),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VDDP", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:1219
    Stanza {
        chips: &[("it8689", 0x8003_0407)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1253
    Stanza {
        chips: &[("it8689", 0x8006_0607)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1290
    Stanza {
        chips: &[
            ("it8689", 0x8008_090A),
            ("it8689", 0x800A_090A),
            ("it8689", 0x8108_090A),
        ],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1321
    Stanza {
        chips: &[("it87952", 0x8008_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("Chipset Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM_CLDO12", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1345
    Stanza {
        chips: &[("it87952", 0x800A_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("Chipset Core", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM_CLDO12", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1373
    Stanza {
        chips: &[("it8689", 0x9003_0406)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1426
    Stanza {
        chips: &[("it8689", 0x9003_0506)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1460
    Stanza {
        chips: &[("it8689", 0x9003_0606)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1517
    Stanza {
        chips: &[("it8696", 0x9004_0507), ("it8696", 0xA004_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:1553
    Stanza {
        chips: &[("it8689", 0x9004_0606)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1589
    Stanza {
        chips: &[("it8689", 0x9005_0506)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1629
    Stanza {
        chips: &[("it8689", 0x9005_0606)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1687
    Stanza {
        chips: &[("it8696", 0x9006_0507), ("it8696", 0xA006_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:1731
    Stanza {
        chips: &[("it8689", 0x9006_0606)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1779
    Stanza {
        chips: &[
            ("it8689", 0x9008_0909),
            ("it8689", 0x9009_0909),
            ("it8689", 0x900A_0909),
            ("it8696", 0x910A_0909),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1816
    Stanza {
        chips: &[("it8792", 0x9008_0909)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("VDD11 SIO", 1.0)),
            (4, named("CPU VDD 18", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1839
    Stanza {
        chips: &[("it8792", 0x9009_0909)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("VDD11 SIO", 1.0)),
            (4, named("CPU VDD 18", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1869
    Stanza {
        chips: &[("it8792", 0x900A_0909), ("it8792", 0x910A_0909)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("VDD11 SIO", 1.0)),
            (4, named("CPU VDD 18", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1896
    Stanza {
        chips: &[("it8696", 0x9103_0506)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1930
    Stanza {
        chips: &[("it8689", 0x9104_0606)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1964
    Stanza {
        chips: &[("it8696", 0x9204_0606)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:1998
    Stanza {
        chips: &[("it8689", 0x9A0A_0908)],
        rails: &[
            (0, named("CPU Vcore0", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU Vcore1", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2032
    Stanza {
        chips: &[("it87952", 0x9A0A_0908)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("CPU VDD11 S3", 1.0)),
            (4, named("CPU VDD18 S5", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2059
    Stanza {
        chips: &[("it8689", 0x9A0B_0908)],
        rails: &[
            (0, named("CPU Vcore0", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU Vcore1", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2093
    Stanza {
        chips: &[("it87952", 0x9A0B_0908)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("CPU VDD11 S3", 1.0)),
            (4, named("CPU VDD18 S5", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2122
    Stanza {
        chips: &[("it8696", 0xA003_0506)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2156
    Stanza {
        chips: &[("it8696", 0xA003_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2190
    Stanza {
        chips: &[("it8696", 0xA003_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2224
    Stanza {
        chips: &[("it8696", 0xA004_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2258
    Stanza {
        chips: &[("it8696", 0xA005_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2292
    Stanza {
        chips: &[("it8696", 0xA005_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2326
    Stanza {
        chips: &[("it8696", 0xA006_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2397
    Stanza {
        chips: &[
            ("it8696", 0xA008_0908),
            ("it8696", 0xA00A_0908),
            ("it8696", 0xA00B_090A),
            ("it8696", 0xA00C_0908),
            ("it8696", 0xA00C_090A),
            ("it8696", 0xA10C_0908),
            ("it8696", 0xA208_090A),
            ("it8696", 0xA308_0908),
            ("it8696", 0xA308_090A),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2443
    Stanza {
        chips: &[("it87952", 0xA008_0908), ("it87952", 0xA308_0908)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2483
    Stanza {
        chips: &[
            ("it8696", 0xA008_090A),
            ("it8696", 0xA00A_090A),
            ("it8696", 0xA108_090A),
            ("it8696", 0xA10A_090A),
            ("it8696", 0xA20A_090A),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2534
    Stanza {
        chips: &[
            ("it87952", 0xA008_090A),
            ("it87952", 0xA108_090A),
            ("it87952", 0xA208_090A),
            ("it87952", 0xA308_090A),
        ],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM VDD1V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2558
    Stanza {
        chips: &[("it87952", 0xA00A_0908)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2591
    Stanza {
        chips: &[
            ("it87952", 0xA00A_090A),
            ("it87952", 0xA10A_090A),
            ("it87952", 0xA20A_090A),
        ],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM VDD1V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2618
    Stanza {
        chips: &[("it87952", 0xA00B_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM VDD1V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2647
    Stanza {
        chips: &[("it87952", 0xA00C_0908)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2678
    Stanza {
        chips: &[("it87952", 0xA00C_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (4, named("CPU VDD18", 1.0)),
            (5, named("PM VDD1V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-amd.conf:2712
    Stanza {
        chips: &[("it8696", 0xA103_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2747
    Stanza {
        chips: &[("it8696", 0xA104_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2781
    Stanza {
        chips: &[("it8696", 0xA106_0507)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VCORE SOC", 1.0)),
            (5, named("CPU VCORE MISC", 1.0)),
            (6, named("CPU VDDIO MEM", 1.0)),
        ],
    },
    // gigabyte-it87-amd.conf:2815
    Stanza {
        chips: &[("it87952", 0xA10C_0908)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PM VCC18", 1.0)),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
];

pub(super) static INTEL: &[Stanza] = &[
    // gigabyte-it87-intel.conf:13
    Stanza {
        chips: &[("it8686", 0x1002_0407)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:48
    Stanza {
        chips: &[("it8686", 0x1003_0407)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:114
    Stanza {
        chips: &[("it8686", 0x1004_0607), ("it8686", 0x3004_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:171
    Stanza {
        chips: &[
            ("it8686", 0x1005_0607),
            ("it8686", 0x1005_060B),
            ("it8686", 0x3005_0607),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:207
    Stanza {
        chips: &[("it8792", 0x1005_060B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:232
    Stanza {
        chips: &[("it8686", 0x1006_090B)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:266
    Stanza {
        chips: &[("it8792", 0x1006_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:299
    Stanza {
        chips: &[
            ("it8686", 0x1008_090B),
            ("it8686", 0x3008_090B),
            ("it8686", 0x3108_090B),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:337
    Stanza {
        chips: &[("it8792", 0x1008_090B), ("it87952", 0x7008_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:362
    Stanza {
        chips: &[("it8686", 0x1108_090B)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:396
    Stanza {
        chips: &[("it8792", 0x1108_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:421
    Stanza {
        chips: &[("it8686", 0x2005_0809)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, Unmapped),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:455
    Stanza {
        chips: &[("it8792", 0x2005_0809)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVPP CH(A/B)", 1.649)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:483
    Stanza {
        chips: &[("it8686", 0x2308_090B), ("it8686", 0x2408_090B)],
        rails: &[
            (0, named("CPU VRIN", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("DRAM CH(D/E/F)", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B/C)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:520
    Stanza {
        chips: &[("it8792", 0x2308_090B), ("it8792", 0x2408_090B)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B/C)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, named("DDRVPP CH(D/E/F)", 1.649)),
        ],
    },
    // gigabyte-it87-intel.conf:580
    Stanza {
        chips: &[("it8686", 0x3002_0407), ("it8686", 0x3102_0407)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:616
    Stanza {
        chips: &[("it8686", 0x3003_0407)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:654
    Stanza {
        chips: &[("it8792", 0x3008_090B), ("it8792", 0x3108_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:683
    Stanza {
        chips: &[("it8686", 0x3105_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:717
    Stanza {
        chips: &[("it8686", 0x3205_0607)],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:794
    Stanza {
        chips: &[
            ("it8686", 0x4002_0407),
            ("it8686", 0x4003_0307),
            ("it8686", 0x4003_0407),
            ("it8686", 0x4004_0607),
            ("it8686", 0x4005_0607),
            ("it8686", 0x4006_090B),
            ("it8686", 0x4008_090A),
            ("it8686", 0x4008_090B),
            ("it8686", 0x4103_0607),
            ("it8686", 0x4106_090B),
            ("it8686", 0x4204_0607),
        ],
        rails: &[
            (0, named("CPU Vcore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:828
    Stanza {
        chips: &[("it8688", 0x4002_0407)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:859
    Stanza {
        chips: &[("it8688", 0x4003_0307)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:890
    Stanza {
        chips: &[("it8688", 0x4003_0407)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:929
    Stanza {
        chips: &[("it8688", 0x4004_0607), ("it8688", 0x4204_0607)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:962
    Stanza {
        chips: &[("it8688", 0x4005_0607)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:996
    Stanza {
        chips: &[("it8688", 0x4006_090B), ("it8688", 0x4106_090B)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1036
    Stanza {
        chips: &[
            ("it8792", 0x4006_090B),
            ("it8792", 0x4106_090B),
            ("it8792", 0x6306_090B),
            ("it8792", 0x6406_090B),
        ],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1070
    Stanza {
        chips: &[("it8688", 0x4008_090A), ("it8688", 0x4008_090B)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1102
    Stanza {
        chips: &[("it8792", 0x4008_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1139
    Stanza {
        chips: &[
            ("it8792", 0x4008_090B),
            ("it8792", 0x6008_090B),
            ("it8792", 0x6308_090B),
        ],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1164
    Stanza {
        chips: &[("it8688", 0x4103_0607)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1222
    Stanza {
        chips: &[
            ("it8688", 0x6002_0407),
            ("it8689", 0x6102_0407),
            ("it8689", 0x7002_0407),
        ],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1263
    Stanza {
        chips: &[("it8688", 0x6003_0407), ("it8689", 0x7003_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1301
    Stanza {
        chips: &[("it8688", 0x6004_0407), ("it8689", 0x7004_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1353
    Stanza {
        chips: &[("it8688", 0x6004_0607), ("it8689", 0x7004_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1398
    Stanza {
        chips: &[("it8688", 0x6005_0607), ("it8689", 0x7005_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1475
    Stanza {
        chips: &[
            ("it8688", 0x6008_090B),
            ("it8688", 0x6108_090A),
            ("it8688", 0x6208_090B),
            ("it8688", 0x6308_090B),
            ("it8688", 0x6508_090B),
            ("it8689", 0x7008_090B),
            ("it8689", 0x7106_090B),
            ("it8689", 0x7108_090B),
            ("it8689", 0x710A_090A),
            ("it8689", 0x710A_090B),
            ("it8689", 0x7208_090B),
            ("it8689", 0x720A_090B),
            ("it8689", 0x7308_090B),
            ("it8689", 0x730A_090B),
        ],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1517
    Stanza {
        chips: &[("it8688", 0x6105_0607), ("it8689", 0x7205_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1551
    Stanza {
        chips: &[("it8792", 0x6108_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PCH Core", 1.0)),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1581
    Stanza {
        chips: &[("it8792", 0x6208_090B), ("it8792", 0x6508_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1605
    Stanza {
        chips: &[("it8688", 0x6303_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1642
    Stanza {
        chips: &[("it8688", 0x6306_090B), ("it8688", 0x6406_090B)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1676
    Stanza {
        chips: &[("it8689", 0x7003_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1711
    Stanza {
        chips: &[("it8689", 0x7006_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCSA", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1745
    Stanza {
        chips: &[("it87952", 0x7106_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1775
    Stanza {
        chips: &[
            ("it87952", 0x7108_090B),
            ("it87952", 0x7208_090B),
            ("it87952", 0x7308_090B),
        ],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1799
    Stanza {
        chips: &[("it87952", 0x710A_090A)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PCH Core", 1.0)),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1833
    Stanza {
        chips: &[
            ("it87952", 0x710A_090B),
            ("it87952", 0x720A_090B),
            ("it87952", 0x730A_090B),
        ],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH Core", 1.0)),
            (4, named("CPU VCCIO", 1.0)),
            (5, named("DDRVPP CH(A/B)", 1.649)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1863
    Stanza {
        chips: &[("it8689", 0x8002_0406)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:1897
    Stanza {
        chips: &[("it8689", 0x8002_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:1944
    Stanza {
        chips: &[("it8689", 0x8003_0406), ("it8689", 0x9003_0406)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2005
    Stanza {
        chips: &[("it8689", 0x8003_0407), ("it8689", 0x9003_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2070
    Stanza {
        chips: &[("it8689", 0x8004_0606), ("it8689", 0x9004_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2134
    Stanza {
        chips: &[("it8689", 0x8004_0607), ("it8689", 0x9004_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2172
    Stanza {
        chips: &[("it8689", 0x8005_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2212
    Stanza {
        chips: &[("it8689", 0x8005_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2272
    Stanza {
        chips: &[("it8689", 0x8006_0606), ("it8689", 0x9006_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2330
    Stanza {
        chips: &[("it8689", 0x8006_0607), ("it8689", 0x9006_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2401
    Stanza {
        chips: &[
            ("it8689", 0x8008_090A),
            ("it8689", 0x800A_0909),
            ("it8689", 0x800A_090A),
            ("it8689", 0x8108_090A),
            ("it8689", 0x810A_090A),
            ("it8689", 0x9008_090A),
            ("it8689", 0x900A_0909),
            ("it8689", 0x900A_090A),
            ("it8689", 0x9108_090A),
            ("it8689", 0x910A_090A),
        ],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2440
    Stanza {
        chips: &[("it87952", 0x8008_090A), ("it87952", 0x9108_090A)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2468
    Stanza {
        chips: &[("it8689", 0x8008_090B), ("it8689", 0x9008_090B)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2507
    Stanza {
        chips: &[("it87952", 0x8008_090B), ("it87952", 0x9008_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("DDRVTT CH(A/B)", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2530
    Stanza {
        chips: &[("it87952", 0x800A_0909)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2557
    Stanza {
        chips: &[("it87952", 0x800A_090A)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2587
    Stanza {
        chips: &[("it8689", 0x8103_0407), ("it8689", 0x9103_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2626
    Stanza {
        chips: &[("it8689", 0x8104_0606), ("it8689", 0x9104_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2662
    Stanza {
        chips: &[("it8689", 0x8104_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2696
    Stanza {
        chips: &[("it8689", 0x8105_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2738
    Stanza {
        chips: &[("it87952", 0x8108_090A), ("it87952", 0x9008_090A)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2770
    Stanza {
        chips: &[
            ("it87952", 0x810A_090A),
            ("it87952", 0x900A_090A),
            ("it87952", 0x910A_090A),
        ],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2809
    Stanza {
        chips: &[("it8689", 0x9005_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2846
    Stanza {
        chips: &[("it8689", 0x9005_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:2880
    Stanza {
        chips: &[("it87952", 0x900A_0909)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, named("PCH 0.82V", 1.0)),
            (4, named("CPU VCCSA", 1.0)),
            (5, named("PCH 1.8V", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2907
    Stanza {
        chips: &[("it8689", 0x9103_0406)],
        rails: &[
            (0, Unmapped),
            (1, Unmapped),
            (2, Unmapped),
            (3, Unmapped),
            (4, Unmapped),
            (5, Unmapped),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2939
    Stanza {
        chips: &[("it8689", 0x9105_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:2974
    Stanza {
        chips: &[("it8689", 0x9106_0606)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3008
    Stanza {
        chips: &[("it8689", 0x9106_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VCCIN AUX", 1.0)),
            (6, named("DRAM CH(A/B)", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3043
    Stanza {
        chips: &[("it8696", 0xA002_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3082
    Stanza {
        chips: &[("it8696", 0xA003_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3121
    Stanza {
        chips: &[("it8696", 0xA003_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3167
    Stanza {
        chips: &[("it8696", 0xA004_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3205
    Stanza {
        chips: &[("it8696", 0xA005_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3254
    Stanza {
        chips: &[("it8696", 0xA006_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3307
    Stanza {
        chips: &[
            ("it8696", 0xA008_090B),
            ("it8696", 0xA009_090B),
            ("it8696", 0xA00A_090B),
            ("it8696", 0xA00B_090B),
            ("it8696", 0xA108_090B),
            ("it8696", 0xA10A_090B),
        ],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3342
    Stanza {
        chips: &[("it87952", 0xA008_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (3, named("CPU VCCIO", 1.0)),
            (4, named("PCH 1.8V", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3367
    Stanza {
        chips: &[("it87952", 0xA009_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (3, named("CPU VCCIO", 1.0)),
            (4, named("PCH 1.8V", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3393
    Stanza {
        chips: &[("it8696", 0xA00A_080B)],
        rails: &[
            (0, named("VCCIN", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("VCCVNN", 1.0)),
            (5, named("PCH 0.82V", 1.0)),
            (6, named("PCH 1.8V", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3427
    Stanza {
        chips: &[("it87952", 0xA00A_080B)],
        rails: &[
            (0, Unmapped),
            (1, named("VCCDHV", 1.0)),
            (2, named("VCCINFAON", 1.0)),
            (3, named("VCCFAEHV", 1.0)),
            (4, named("VCCFAFIVRA", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3455
    Stanza {
        chips: &[("it87952", 0xA00A_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (3, named("CPU VCCIO", 1.0)),
            (4, named("PCH 1.8V", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3483
    Stanza {
        chips: &[("it87952", 0xA00B_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (3, named("CPU VCCIO", 1.0)),
            (4, named("PCH 1.8V", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3513
    Stanza {
        chips: &[("it8696", 0xA102_0407)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3552
    Stanza {
        chips: &[("it8696", 0xA103_0607), ("it8696", 0xA203_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3587
    Stanza {
        chips: &[("it8698", 0xA104_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3624
    Stanza {
        chips: &[("it8696", 0xA106_0607)],
        rails: &[
            (0, named("CPU VCore", 1.0)),
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (4, named("CPU VAXG", 1.0)),
            (5, named("CPU VNNAON", 1.0)),
            (6, named("CPU VCCSA", 1.0)),
        ],
    },
    // gigabyte-it87-intel.conf:3660
    Stanza {
        chips: &[("it87952", 0xA108_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (3, named("CPU VCCIO", 1.0)),
            (4, named("PCH 1.8V", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // gigabyte-it87-intel.conf:3684
    Stanza {
        chips: &[("it87952", 0xA10A_090B)],
        rails: &[
            (0, Unmapped),
            (1, named("CPU VDD2", 1.0)),
            (2, named("PCH 0.82V", 1.0)),
            (3, named("CPU VCCIO", 1.0)),
            (4, named("PCH 1.8V", 1.0)),
            (5, Unmapped),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:8 and gigabyte-it87-intel-skylakex.conf:8
    Stanza {
        chips: &[("it8686", 0x2005_080B)],
        rails: &[
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (5, named("CPU VCCSA", 1.0)),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:55 and gigabyte-it87-intel-skylakex.conf:55
    Stanza {
        chips: &[
            ("it8686", 0x2008_090B),
            ("it8686", 0x2108_090B),
            ("it8686", 0x2208_090B),
        ],
        rails: &[
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (5, named("CPU VCCSA", 1.0)),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:93 and gigabyte-it87-intel-skylakex.conf:93
    Stanza {
        chips: &[("it8688", 0x5008_090A), ("it8688", 0x5108_090A)],
        rails: &[
            (1, named("+3.3V", 1.649)),
            (2, named("+12V", 6.0)),
            (3, named("+5V", 2.5)),
            (5, named("CPU VCCSA", 1.0)),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:129 and gigabyte-it87-intel-skylakex.conf:129
    Stanza {
        chips: &[("it8792", 0x2005_080B)],
        rails: &[
            (0, Unmapped),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:159 and gigabyte-it87-intel-skylakex.conf:159
    Stanza {
        chips: &[("it8792", 0x2008_090B)],
        rails: &[
            (0, Unmapped),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:187 and gigabyte-it87-intel-skylakex.conf:187
    Stanza {
        chips: &[("it8792", 0x2108_090B), ("it8792", 0x2208_090B)],
        rails: &[
            (0, Unmapped),
            (2, named("PCH Core", 1.0)),
            (3, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
    // X299, agreed inputs only: gigabyte-it87-intel-kabylakex.conf:215 and gigabyte-it87-intel-skylakex.conf:215
    Stanza {
        chips: &[("it8792", 0x5008_090A), ("it8792", 0x5108_090A)],
        rails: &[
            (0, Unmapped),
            (2, Unmapped),
            (4, named("CPU VCCIO", 1.0)),
            (6, Unmapped),
            (7, Unmapped),
            (8, Unmapped),
        ],
    },
];
